[package]
name = "omnicompress-py"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "omnicompress"
crate-type = ["cdylib"]

[dependencies]
omnicompress-core = { path = "../omnicompress-core" }
pyo3 = { version = "0.22", features = ["extension-module"] }
serde_json = "1"
